"""add roles_select_title

Revision ID: 102edc087b1a
Revises: 9c8f42a9162c
Create Date: 2026-08-30 03:58:09.903677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '102edc087b1a'
down_revision: Union[str, Sequence[str], None] = '9c8f42a9162c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('roles_select_title', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'roles_select_title')
    # ### end Alembic commands ###
