"""add users count_messages and count_voice_minutes

Revision ID: 82bfe2d00147
Revises: 6985bc6328b5
Create Date: 2026-08-29 23:21:06.488782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bfe2d00147'
down_revision: Union[str, Sequence[str], None] = '6985bc6328b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'users',
        sa.Column('count_messages', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    op.add_column(
        'users',
        sa.Column('count_voice_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'count_voice_minutes')
    op.drop_column('users', 'count_messages')
    # ### end Alembic commands ###
