"""unique users by user_id and guild

Revision ID: 879df5d6e7d1
Revises: 82bfe2d00147
Create Date: 2026-08-30 01:26:14.351184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '879df5d6e7d1'
down_revision: Union[str, Sequence[str], None] = '82bfe2d00147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_user_id'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_user_id_guild_settings_id', 'users', ['user_id', 'guild_settings_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_users_user_id_guild_settings_id', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_user_id'), 'users', ['user_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
