"""add join_role_id to guild_settings

Revision ID: 9c8f42a9162c
Revises: b3d19c06caf6
Create Date: 2026-08-30 03:26:50.877748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c8f42a9162c'
down_revision: Union[str, Sequence[str], None] = 'b3d19c06caf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guild_settings', sa.Column('join_role_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'join_role_id')
    # ### end Alembic commands ###
