"""add roles select message and role reactions

Revision ID: b3d19c06caf6
Revises: 879df5d6e7d1
Create Date: 2026-08-30 03:02:57.772347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d19c06caf6'
down_revision: Union[str, Sequence[str], None] = '879df5d6e7d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guild_role_reactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('guild_settings_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=80), nullable=False),
    sa.Column('role_id', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['guild_settings_id'], ['guild_settings.id'], name=op.f('fk_guild_role_reactions_guild_settings_id_guild_settings')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guild_role_reactions')),
    sa.UniqueConstraint('guild_settings_id', 'emoji', name='uq_guild_role_reactions_guild_emoji')
    )
    op.add_column('guild_settings', sa.Column('roles_select_message', sa.Text(), nullable=True))
    op.add_column('guild_settings', sa.Column('roles_select_channel_id', sa.String(length=20), nullable=True))
    op.add_column('guild_settings', sa.Column('roles_select_message_id', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guild_settings', 'roles_select_message_id')
    op.drop_column('guild_settings', 'roles_select_channel_id')
    op.drop_column('guild_settings', 'roles_select_message')
    op.drop_table('guild_role_reactions')
    # ### end Alembic commands ###
